/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
const computed: typeof import('vue')['computed'];
const reactive: typeof import('vue')['reactive'];
const ref: typeof import('vue')['ref'];
const watch: typeof import('vue')['watch'];
}
